#-------------------------------------------
#          ZhengCraft Config
#-------------------------------------------

#----------[General Settings]---------------
general_settings:
  power: 2
  on_fire: true